### ISSUE TITLE
kernel panic upon loading tvheadend

### ISSUE THREAD

**Issue by tcamargo** [th0ma7/synology#5]
Hi,

Did you manage to solve issue you posted to the linux-media ml?

https://www.spinics.net/lists/linux-media/msg175724.html

I did a similar setup for my Synology NAS (see https://github.com/tcamargo/dsm-media_build). It was working great until the DSM 6.2.3 update. I managed to get media_build compiled again today hoping a new version would solve the problem.

Thanks!

Best regards,
Tiago

**Comment by th0ma7** [comment]
Sadly no I didn't and haven't received any feedback yet neither.
I did opened-up an issue to @b-rad-NDi who is one of the key "maintainers" for Hauppauge drivers in hope to get a solution: https://github.com/b-rad-NDi/Embedded-MediaDrivers/issues/10
Feel free to add-up comments of yours which may help getting additional attention and replying to the media_tree thread online.

**Comment by tcamargo** [comment]
Have you heart back from Synology regarding and up to date toolchain?

**Comment by th0ma7** [comment]
not yet but this morning there I received a DSM-7 preview program email... So my guess is that DSM7 sources + 6.2.3 sources may become available real soon... (fingers crossed).

**Comment by tcamargo** [comment]
> not yet but this morning there I received a DSM-7 preview program email... So my guess is that DSM7 sources + 6.2.3 sources may become available real soon... (fingers crossed).

Thanks for the update!

**Comment by tcamargo** [comment]
Tried to contact Synology support. 

> I understand ever since updating DSM a module you use hasn't worked. I can't provide up-to-date toolchains yet as our devs delay the release. If you'd like you can submit a feature suggestion that goes straight to our devs to either re-add support for the module, or provide the toolchain. You can submit that request here: https://www.synology.com/en-us/form/inquiry/feature

I opened a feature request. Let's see..

**Comment by Selfmade-RuLeZ** [comment]
Hi, jumped into the same issue, now i found the sources for the 6.2.3 toolchain got released about two weeks ago. 
If you can play with it, here they are: https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.3%20Tool%20Chains/
Sadly, the kernel sources are not released yet
Edit: Just kick me in the ... if they already were released in september :D You need the kernel source, right?
Edit2: Can't build it with new Toolchain, is it necessary to use Ubuntu 18.x and not Ubuntu 20.x? 
`too few arguments to function 'get_user_pages'` in `include/linux/mm.h`
Think its something todo with the new linux clinch against Proprietary Video Drivers?
My OS Lecture is some long time ago :grin:

**Comment by th0ma7** [comment]
Long storty short, you need the exact matching kernel sources to be able to build modules against it.  Usually things will work all-right between stable series but jumps to higher version will not.

From my reading, the reasons behind the crash is due to Meltdown, Spectre, L1TF and other Intel CPU flaws.  Fixes for these have possibly been backported over the kernel between the release of the 6.2.2 sources vs current 6.2.3.  Thus any modules built against a previous version of the kernel will have issues as not running against this new code which is quite invasive.

I've asked this week, again, to Synology about 6.2.3 source.  Still waiting to hear more, pending a resolution.  I've also asked the same for DSM-7 preview release as we will end-up there at a point or another.  Wait & see.

**Comment by tcamargo** [comment]
> Hi, jumped into the same issue, now i found the sources for the 6.2.3 toolchain got released about two weeks ago.
> If you can play with it, here they are: https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.3%20Tool%20Chains/
> Sadly, the kernel sources are not released yet
> Edit: Just kick me in the ... if they already were released in september :D You need the kernel source, right?
> Edit2: Can't build it with new Toolchain, is it necessary to use Ubuntu 18.x and not Ubuntu 20.x?
> `too few arguments to function 'get_user_pages'` in `include/linux/mm.h`
> Think its something todo with the new linux clinch against Proprietary Video Drivers?
> My OS Lecture is some long time ago 😁

You can probably circumvent that with some media_build tweaks. Anyway, we need new kernel sources..

**Comment by tcamargo** [comment]
No reply back from Synology so far. Losing hope...

**Comment by Selfmade-RuLeZ** [comment]
well known that Synology is abusing the GPL License by delaying release of GPL source code.
Other interesting story: 
On the Xpenology Forums they said, that kernel modules build with 6.2.0 are running fine with 6.2.3 as they revoked changes from 6.2.2 kernel. 
Maybe you could try this? I get those user pages errors, but this time in the videobuf-dma-sg.c file
```
/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.c: In function 'videobuf_dma_init_user_locked':
/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.c:188:16: warning: passing argument 6 of 'get_user_pages' makes integer from pointer without a cast
         flags, dma->pages, NULL);
                ^
In file included from include/linux/scatterlist.h:7:0,
                 from include/linux/dma-mapping.h:10,
                 from include/linux/skbuff.h:34,
                 from include/linux/if_ether.h:23,
                 from /kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/compat.h:1721,
                 from <command-line>:0:
include/linux/mm.h:941:6: note: expected 'int' but argument is of type 'struct page **'
 long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
      ^
/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.c:186:8: error: too few arguments to function 'get_user_pages'
  err = get_user_pages(current, current->mm,
        ^
In file included from include/linux/scatterlist.h:7:0,
                 from include/linux/dma-mapping.h:10,
                 from include/linux/skbuff.h:34,
                 from include/linux/if_ether.h:23,
                 from /kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/compat.h:1721,
                 from <command-line>:0:
include/linux/mm.h:941:6: note: declared here
 long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
      ^
/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation"
scripts/Makefile.build:264: recipe for target '/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.o' failed
make[2]: *** [/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l/videobuf-dma-sg.o] Error 1
Makefile:1411: recipe for target '_module_/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l' failed
make[1]: *** [_module_/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l] Error 2
make[1]: Leaving directory '/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/linux-4.4.x'
Makefile:51: recipe for target 'default' failed
make: *** [default] Error 2
make: Leaving directory '/kernel/Embedded-MediaDrivers/build/SYNOAPOLLOLAKE/media_build/v4l'
```

**Comment by tcamargo** [comment]
@Selfmade-RuLeZ could you please share a link relevant threads?

**Comment by Selfmade-RuLeZ** [comment]
https://xpenology.com/forum/topic/21663-driver-extension-jun-103b104b-for-dsm622-for-3615xs-3617xs-918/page/35/?tab=comments#comment-178925

> but thats all not so important anymore because with 6.2.3 synology returned the state of the kernel it had with 6.2.0 so in scenario 1 after install you will of dsm you will have kernel 6.2.3 on usb but the "old" 6.2.0 drivers are still working with 6.2.3 so the system will boot, only flaw is the i915 driver in 918+ loader (see explanation below)

**Comment by tcamargo** [comment]
Did you manage to create new working modules? I reused an old build and my Synology is still crashing.

**Comment by Selfmade-RuLeZ** [comment]
Unfortunately no, so I think the post is sadly only related to ethernet modules. 
I will try it tomorrow with another dvb client/program to clearify that it‘s not tvheadend related

**Comment by tcamargo** [comment]
> Unfortunately no, so I think the post is sadly only related to ethernet modules.
> I will try it tomorrow with another dvb client/program to clearify that it‘s not tvheadend related

Thx! Keep us posted. Plan B? Complain to FSF?

**Comment by Selfmade-RuLeZ** [comment]
Also kernel panic with minisatip (privileged docker setup), so I think it's not tvheadend related.

**Comment by tcamargo** [comment]
> Also kernel panic with minisatip (privileged docker setup), so I think it's not tvheadend related.

I opened yet another ticket to them. Now demanding compliance to GPL... No hope to get something, but I'm out of ideas besides filing a complain to FSF.

**Comment by th0ma7** [comment]
On my end I'm also in communication with Synology related to on-going discussions with the SynoCommunity that I am into (e.g. spksrc).  I've been asking them for 6.2.3-25426 source code since weeks (and 7.0-beta) with no success.

Tonight I just received a relatively positive answer as to the possibility of providing it... fingers crossed that it will indeed happen before long.  I'll keep you posted.

**Comment by tcamargo** [comment]
> Hello,
> 
> The source is on slate for release but hasn't been actually released yet. We don't have a particular roadmap we follow, but it is on the way. A lot of the times, the source is released close to the next DSM update, so I would check back around that time.
> 
> Thanks,

**Comment by tcamargo** [comment]
Any news?

**Comment by th0ma7** [comment]
nope.

**Comment by th0ma7** [comment]
Heads-up, they just released the kernel code for 6.2.3... 
https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/

Being added to spksrc (SynoCommunity)
https://github.com/SynoCommunity/spksrc/pull/4399

**Comment by tcamargo** [comment]
Thanks! Eager to test your scripts ;)

**Comment by th0ma7** [comment]
**Update January 22nd 2021: Please use follow-up thread located here: https://github.com/th0ma7/synology/issues/8**

---

First set of experimental LinuxTV packages for Synology 6.2.3 x86_64 archs available at:
* https://github.com/th0ma7/synology/tree/master/packages/linuxtv

It currently only loads high level modules:
* `rc/rc-core.ko`
* `mc/mc.ko`
* `v4l2-core/videodev.ko`
* `common/tveeprom.ko`
* `common/videobuf2/videobuf2-common.ko`
* `common/videobuf2/videobuf2-v4l2.ko`
* `common/videobuf2/videobuf2-memops.ko`
* `common/videobuf2/videobuf2-vmalloc.ko`
* `dvb-core/dvb-core.ko`

The default start_stop calls my generic script located at `/var/packages/linuxtv/target/bin/linuxtv.sh`
Modules are located at `/var/packages/linuxtv/target/lib/modules`
Firmware are located under `/var/packages/linuxtv/target/lib/firmware`

In order to get your device working you will need to manually `insmod` the relevant modules in the right order and follow-up the dmesg output.  It isn't that trivial but it should normally work.

For instance, Hauppauge WinTV would require the following modules to be loaded manually:
1. `em28xx_dvb`
2. `em28xx`
3. `lgdt3306a`
4. `si2157`

**IMPORTANT NOTE:** This is highly experimental at this stage, upon loading a module you might experience a NAS reboot (was hapening when trying to load DSM-6.1 modules against DSM-6.2.3 kernel).
